# Generated by Django 5.1.7 on 2025-04-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_employee_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assigned_to',
        ),
    ]
